version: '3'

services:
  spark:
    image: apache/spark:3.3.2
    ports:
      - "8080:8080"
      - "8888:8888"
    environment:
      - SPARK_MASTER_HOST=spark
      - SPARK_MASTER_PORT=7077
      - SPARK_LOCAL_IP=127.0.0.1
      - ENABLE_INIT_DAEMON=false
    volumes:
      - ./notebooks:/opt/notebooks
    networks:
      - spark

  jupyter:
    image: jupyter/all-spark-notebook
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/home/jovyan/work
    environment:
      - SPARK_URL=spark://spark:7077
    depends_on:
      - spark
    networks:
      - spark

networks:
  spark: